name: weight_control
description: "An app to control your weight"
publish_to: "none"
repository: https://github.com/meg4cyberc4t/weight_control
issue_tracker: https://github.com/meg4cyberc4t/weight_control/issues
topics: ["flutter", "education", "health"]

version: 0.0.1+1

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.6"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
