name: weight_control
description: "An app to control your weight and analyze"
publish_to: "none"
repository: https://github.com/meg4cyberc4t/weight_control
issue_tracker: https://github.com/meg4cyberc4t/weight_control/issues
topics: ["flutter", "education", "health"]

version: 0.0.1+1

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.6"

dependencies:
  cupertino_icons: ^1.0.6
  drift: ^2.15.0
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  logging: ^1.2.0
  meta: ^1.10.0
  octopus: ^0.0.8
  package_info_plus: ^8.0.0
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  url_launcher: ^6.2.4
  freezed_annotation: ^2.4.1
  sqlite3_flutter_libs: ^0.5.20
  syncfusion_flutter_charts: ^25.1.35
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  intl_utils: ^2.8.7
  freezed: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/localizations
  output_dir: lib/src/common/localizations/generated
  use_deferred_loading: false

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon_source.jpeg"
  min_sdk_android: 21
  ios: true
