name: weight_control
description: "An app to control your weight"
publish_to: "none"
repository: https://github.com/meg4cyberc4t/weight_control
issue_tracker: https://github.com/meg4cyberc4t/weight_control/issues
topics: ["flutter", "education", "health"]

version: 0.0.1+1

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.6"

dependencies:
  cupertino_icons: ^1.0.6
  drift: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  logging: ^1.2.0
  meta: ^1.10.0
  octopus: ^0.0.8
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  drift_dev: ^2.15.0

flutter:
  uses-material-design: true
